### PR TITLE
Add environment widget example

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Builds on #3 and #26. Review those ones first!

The `EnvironmentWidgetBase` class enables you to manage variable values from a combination of

- custom variable values
- environment variables
- user input.

(listed by order of precedence)

For example you might not have the resources to provide an `OPENAI_API_KEY`, `WEAVIATE_API_KEY` or
`LANGCHAIN_API_KEY`. In that case you would would like to ask the user for it.

Inherit from this widget to create your own custom `EnvironmentWidget`.

This widget can make it easy to run the app in different environments

- locally: all keys might be set in `os.environ`
- hugging face: some keys might not be set in `os.environ` due to costs, but users can manually provide them.

image

After setting the `WEAVIATE_API_KEY` it looks like

image

See https://github.com/holoviz/panel/issues/5562 for more detail. Long term I think it could be useful if something like this was included in the Panel chat components.

### CODE REVIEW

**Comment by ahuang11** [comment]
I wasn't aware that there's a langchain API key.

**Comment by MarcSkovMadsen** [comment]
Me neither. I just saw it in an example

**Comment by MarcSkovMadsen** [comment]
At least Langchain puts its an API key in their docs. This is where I saw it

https://github.com/langchain-ai/chat-langchain

image

**Comment by MarcSkovMadsen** [comment]
I've merged with the current main branch. And everything should be ready to merge.

If you want, I can change the example to use another variable than the `LANGCHAIN_API_KEY`. Let me know.

If anything else is needed let me know.

**Review by ahuang11 — APPROVED** [review]

**Comment by ahuang11** [comment]
Thanks for contributing this! I'd love to migrate this into Panel too if Philipp agrees!

**Pull request merged**
