### PR TITLE
Update thumbnails automatically

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
DON'T MERGE YET. MORE WORK TO BE DONE!

Depends on #12. Please review that one first.

You can generate the thumbnails via

```
SCREENSHOT=true hatch run pytest -m ui
cp tests/ui/screenshots/* docs/assets/thumbnails/
```

I don't think the screenshots are yet meaningful enough. We should refactor the examples to make it very easy to understand what they are about from a screenshot. Alternatively we could agree to use manual screenshots?

What do you think @ahuang11 ?

### CODE REVIEW

**Comment by ahuang11** [comment]
I agree with you that they're not really helpful at this moment.

I think to make them useful, we should somehow detect that it's getting a screenshot and programmatically send a message to trigger a response and then grab a screenshot after waiting 5s.

Also, we should add titles to each of the ChatInterface.

Or ideally, we manually create GIFs of them which is much more intriguing than screenshots.

**Comment by MarcSkovMadsen** [comment]
Yes. My thoughts are

- We could use playwright to interact with the live application before taking the screenshot.
- In addition to taking a screenshot it could also record a video.
- We could automatically convert those videos to gifs
- We could the show gif instead of image when a user hover over the image ?
- In addition we could autogenerate links in the `index.md` to quickly share on social media with text and gif.

**Comment by MarcSkovMadsen** [comment]
One issue currently is that Playwright does not show the emojis when taking screenshots

image

**Comment by MarcSkovMadsen** [comment]
I got the automation concept for screenshot and video working. The below is automatically recorded for `echo.py`.

[3499ef8039af2b1a223a0f07c600bee0.webm](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/b2a44632-a58a-42ec-a545-37cb29d5e260)

test-finished-1

**Comment by ahuang11** [comment]
Thanks! I'll fix the tests in another branch.

**Comment by MarcSkovMadsen** [comment]
We should coordinate a bit @ahuang11 . I'm implementing the playwright/ video code here #41

**Pull request merged**
