### PR TITLE
Add ChatInput and Status components

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
As discussed in https://github.com/holoviz/panel/pull/5670, moves the `ChatInput` and `Status` components to `panel-chat-examples` where they can live until Panel gets similar built in components.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
The two failing tests are due to mistral_and_llama png and mo4. I don't think I've caused that @ahuang11 ?

**Comment by ahuang11** [comment]
On second thought, I suppose if we have it here, this repo shouldn't be called panel-chat-examples. Also, it's not easily `pip install`able since this package isn't published to PyPi.

**Comment by MarcSkovMadsen** [comment]
Agree. Right now they are here `panel-chat-examples` provide a temporary home. We can iterate on them here and get some community feedback. When/ if more is done they can be moved to `panel` or another `panel-xyz` package.

**Comment by MarcSkovMadsen** [comment]
This PR also includes changes to the autogenerated files due to #71.

@ahuang11 . I believe this should be ready to merge. Otherwise let me know. Thanks.

**Review by ahuang11 — APPROVED** [review]

**Pull request merged**
