### PR TITLE
Improve social card

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
I don't think the social card is great. I've created one with DALL E which I think works better.

## Prompt

Background:
Use a friendly, pastel-colored background to give the card a warm and inviting feel. You could use shades of blue and green to evoke a sense of accessibility and inclusivity.

Title:
At the top display the title "Panel Chat Examples"

Image:
In the center of the card, place a cute chat bubble. Inside the chat bubble, display a friendly chat prompt.

Call to Action (CTA):
Include a button with a contrasting color that stands out. The text on the button/link should say, "Explore Now."

Additional Design Elements:
You can add small, subtle illustrations or icons related to chat or coding around the card to enhance its visual appeal and reinforce the project's theme.

Remember to maintain a clean and uncluttered design, keeping the focus on the chat prompt and the call to action. Once you have this description, you can work with a graphic designer or use a design tool like Canva to create the social media card.

### CODE REVIEW

**Comment by ahuang11** [comment]
Seems like it's very tall vertically. Should social cards be that tall?

**Comment by MarcSkovMadsen** [comment]
They can be 1:1 or 2:1

**Comment by ahuang11** [comment]
Do we need to update / delete scripts/social_card.py?

**Comment by MarcSkovMadsen** [comment]
> Do we need to update / delete scripts/social_card.py?

Deleted

**Pull request merged**
